#!/usr/bin/env bash

cd "$( dirname "${BASH_SOURCE[0]}" )/.."
if [ -f secure_password ]; then
  secure_password=$(cat secure_password)
fi
if [ -z ${secure_password+x} ]; then
  echo "decrypt failed: secure_password was not provided"
  exit 1
fi
openssl aes-256-cbc -k "${secure_password}" -in secure.tar.gz.enc -out secure.tar.gz -d
tar xzf secure.tar.gz
rm secure.tar.gz
