#!/usr/bin/env bash

cd "$( dirname "${BASH_SOURCE[0]}" )/.."
if [ -f secure_password ]; then
  secure_password=$(cat secure_password)
fi
if [ -z ${secure_password+x} ]; then
  echo "encrypt failed: secure_password was not provided"
  exit 1
fi
tar czf secure.tar.gz secure
openssl aes-256-cbc -k "${secure_password}" -in secure.tar.gz -out secure.tar.gz.enc
rm secure.tar.gz
